language: r

r:
  - bioc-devel
  - bioc-release
  
# Strict checks in place
warnings_are_errors: false

branches:
  only:
    - master

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

